KrishiChaupal/CropSuggestion/urls.py
from django.conf.urls import url
from . import views

app_name='CropSuggestion'

urlpatterns=[
    url(r'^$',views.suggest.as_view(),name="suggest"),
    url(r'weather/',views.weather.as_view(),name="weather"),
]

KrishiChaupal/QualityCheck/urls.py
from django.conf.urls import url
from . import views

app_name='QualityCheck'

urlpatterns=[
    url(r'^$',views.UploadImage_view,name='UploadImage_view'),

]

KrishiChaupal/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import SignUp

app_name='accounts'

urlpatterns= [
    url(r'login/$',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',SignUp.as_view(),name='signup')
]

KrishiChaupal/broadcast/urls.py
from django.conf.urls import url
from . import views

app_name='broadcast'

urlpatterns=[
    url(r'^$',views.broadcast_sms,name="broadcast_sms"),
]

KrishiChaupal/krishi_chaupal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^about/',views.AboutPage.as_view(),name='about'),
    url(r'^faq/',views.faq.as_view(),name='faq'),
    url(r'^rice/',views.rice.as_view(),name='rice'),
    url(r'^wheat/',views.wheat.as_view(),name='wheat'),
    url(r'^sugarcane/',views.sugarcane.as_view(),name='sugarcane'),
    url(r'^risks/',views.risks.as_view(),name='risks'),
    url(r'^maize/',views.maize,name='maize'),
    url(r'^readmore/',views.readmore.as_view(),name='readmore'),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    # url(r'chatbot/',include('chatbot.urls',namespace='chatbot')),
    url(r'broadcast/',include('broadcast.urls',namespace='broadcast')),
    url(r'loans/',include('loans.urls',namespace='loans')),
    url(r'QualityCheck/',include('QualityCheck.urls',namespace='QualityCheck')),
    url(r'CropSuggestion/',include('CropSuggestion.urls',namespace='CropSuggestion')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KrishiChaupal/loans/urls.py
from django.conf.urls import url
from . import views

app_name='loans'

urlpatterns=[
    url(r'canara/$',views.canara.as_view(),name="canara"),
    url(r'cbi/',views.cbi,name="cbi"),
    url(r'bom/',views.loan.as_view(),name="bom"),
    url(r'cb/',views.loan.as_view(),name="cb"),
    url(r'iob/',views.iob,name="iob"),
    url(r'uco/',views.loan.as_view(),name="uco"),
    url(r'bb/',views.loan.as_view(),name="bb"),
]

KrishiChaupal/templates/about.html
{% extends "base.html" %}
    <!-- Header part end-->
{% load static %}
{% block content %}

    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>About Us</h2>
                            <p>Home<span>/</span>About Us</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->


   <!--::review_part start::-->
    <section class="special_cource padding_top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5">
                    <div class="section_tittle text-center">
                        <h2>A Site For Farmers</h2>
                    </div>
                </div>
            </div>
                	<div class="col-lg-12" align='center'>

                        		<h5>Farmer is considered as the backbone of Indian economy. If the farmer do good then it is beneficial for the farmer and also for the country.Services sector is the largest sector of India.
Gross Value Added (GVA) at current prices for Services sector is estimated at 92.26 lakh crore INR in 2018-19. Services sector accounts for 54.40% of total India's GVA of 169.61 lakh
crore Indian rupees. With GVA of Rs. 50.43 lakh crore, Industry sector contributes 29.73%. While, Agriculture and allied sector shares 15.87%.</h5>
                    		<br> <br> <br>
               		</div>

		</div>
        </div>
    </section>
    <!--::blog_part end::-->
<!--::review_part start::-->
    <section class="special_cource ">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5">
                    <div class="section_tittle text-center">
                        <h2>Agriculture Is Lifeline</h2>
                    </div>
                </div>
            </div>
                	<div class="col-lg-12" align='center'>

                        		<h5>At 2011-12 prices, composition of Agriculture & allied, Industry, and Services sector are 14.39%, 31.46%, and 54.15%, respectively.Share of primary (comprising agriculture, forestry,
fishing and mining & quarrying), secondary (comprising manufacturing, electricity, gas, water supply & other utility services, and construction) and tertiary (services) sectors have been
estimated as 18.57 per cent, 27.03 per cent and 54.40 per cent.According to CIA Fackbook sector wise Indian GDP composition in 2017 are as follows : Agriculture (15.4%), Industry (23%)
and Services (61.5%). With production of agriculture activity of $375.61 billion, India is 2nd larger producer of agriculture product. India accounts for 7.39 percent of total global
agricultural output.</h5>
                    	<br> <br> <br>
               		</div>
		</div>
        </div>
    </section>
    <!--::blog_part end::-->
<!--::review_part start::-->
    <section class="special_cource ">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-5">
                    <div class="section_tittle text-center">
                        <h2>What We Provide</h2>
                    </div>
                </div>
            </div>
                	<div class="col-lg-12" align='center'>

                        		<h5>Farmers friend is a web portal designed to help farmers to produce the high yield at the minimum cost and efforts of farmer.It is designed aiming to Helping the farmers in terms of Crop
suggestion includes which type of crop require more water,type of soil,weather conditions etc.Provides precautions based on the meteorological department forecast of rainfall and weather
conditions.It can help in predicting possible pest, insect attacks so that the farmer is well prepared, weather warnings etc.It provides details to farmers on weather patterns that could
impact the crop.It provides Steps for producing high yield that are specific for a farmer based on the local, regional terrain , weather scenario , rather than generic guidance.It also
provides Better Farmer Financial Inclusion for planning out loans , interest and managing his costs.The Purpose of this analysis is beneficial for Farmers, Pesticide firms , Govt agencies
helping farmers , Agriculture loan banks.
</h5>
                    	<br> <br> <br>
               		</div>
		</div>
        </div>
    </section>
    <!--::blog_part end::-->

    <!-- footer part start-->
    <footer class="footer-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-md-4 col-xl-3">
                    <div class="single-footer-widget footer_1">
                        <a href="index.html"> <img src="{% static 'krishi_chaupal/img/logo.png' %}" alt=""> </a>
                        <p>But when shot real her. Chamber her one visite removal six
                            sending himself boys scot exquisite existend an </p>
                        <p>But when shot real her hamber her </p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-4">
                    <div class="single-footer-widget footer_2">
                        <h4>SMS Broadcast</h4>
                        <p>Stay updated with our latest trends Seed heaven so said place winged over given forth fruit.
                        </p>


                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Enter Phone Number'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter phone number'">
                                    <div class="input-group-append">
                                        <button class="btn btn_1" type="button"><i class="ti-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>



                        <div class="social_icon">
                            <a href="#"> <i class="ti-facebook"></i> </a>
                            <a href="#"> <i class="ti-twitter-alt"></i> </a>
                            <a href="#"> <i class="ti-instagram"></i> </a>
                            <a href="#"> <i class="ti-skype"></i> </a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-md-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Contact us</h4>
                        <div class="contact_info">
                            <p><span> Address :</span> Hath of it fly signs bear be one blessed after </p>
                            <p><span> Phone :</span> +2 36 265 (8060)</p>
                            <p><span> Email : </span>info@colorlib.com </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </footer>
    <!-- footer part end-->


    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="js/swiper.min.js"></script>
    <!-- swiper js -->
    <script src="js/masonry.pkgd.js"></script>
    <!-- particles js -->
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.nice-select.min.js"></script>
    <!-- swiper js -->
    <script src="js/slick.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <!-- custom js -->
    <script src="js/custom.js"></script>

{% endblock %}

KrishiChaupal/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Krishi Chaupal</title>
    <link rel="icon" href="{static 'img/favicon.png' %}">
      <link rel="icon" href="{% static 'img/ourlogo.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/owl.carousel.min.css' %}">
    <!-- themify CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/themify-icons.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/flaticon.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'krishi_chaupal/css/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel="stylesheet" href="{% static 'krishi_chaupal/css/stylechat.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light">

                      <div class="navbar-brand"> 
                      <img src="{%static 'krishi_chaupal/img/logo.png' %}" alt="" class="logo"> 
                      </div>

                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'about' %}">About</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'CropSuggestion:suggest' %}">Forecast and Advisory</a>
                                </li>



                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" 				aria-expanded="false"> Loans
                                    </a>


                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'loans:canara' %}">Canara Bank</a>
                                        <a class="dropdown-item" href="{% url 'loans:cbi' %}">Central Bank of India</a>
                                        <a class="dropdown-item" href="{% url 'loans:bom'%}">Bank of Maharastra</a>
                                        <a class="dropdown-item" href="{% url 'loans:cb' %}">corporative Bank</a>
                                        <a class="dropdown-item" href="{% url 'loans:iob' %}">Indian Overseas Bank</a>
                                        <a class="dropdown-item" href="{% url 'loans:uco' %}">UCO Bank</a>
                                        <a class="dropdown-item" href="{% url 'loans:bb' %}">Bihar bank</a>
                                    </div>
                                </li>

  {% if user.is_authenticated %}

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'QualityCheck:UploadImage_view' %}">AI quality check</a>
                                </li>
{% endif %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="crop.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-							haspopup="true" aria-expanded="false"> Major Crops
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'rice' %}">Rice</a>
                                        <a class="dropdown-item" href="{% url 'wheat' %}">Wheat</a>
                                        <a class="dropdown-item" href="{% url 'sugarcane' %}">Sugar Cane</a>
                                        <a class="dropdown-item" href="{% url 'maize' %}">Maize</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'faq' %}">FAQ</a>
                                    </li>

                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                  <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                                </li>
                                {% else %}
                                <li>
                                  <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                                {% endif %}

                                <li>
                                <a class="nav-link" href="{% url 'broadcast:broadcast_sms' %}">SMS Broadcast</a>
                              </li>

                                <li class="d-none d-lg-block">
                                    <a class="btn_1" href="{% url 'risks' %}">Risks & Their Management</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>

{% block content %}
{% endblock %}

{% if user.is_authenticated %}

<div id="chat-circle" class=" btn-raised">
<svg class="icon-speech" viewBox="0 0 48 48">
      <use xlink:href="#icon-speech" />
    </svg>	</div>

<div class="chatbot chatbot--closed ">
  <div class="chatbot__header">
    <p><strong>Meghdoot <span class="u-text-highlight"></span></strong></p>
    <svg class="chatbot__close-button icon-speech" viewBox="0 0 32 32">
      <use xlink:href="#icon-speech" />
    </svg>
    <svg class="chatbot__close-button icon-close" viewBox="0 0 32 32">
      <use xlink:href="#icon-close" />
    </svg>
  </div>
  <div class="chatbot__message-window">
    <ul class="chatbot__messages">
      <li class="is-ai animation">
        <div class="is-ai__profile-picture">
          <svg class="icon-avatar" viewBox="0 0 32 32">
            <use xlink:href="#avatar" />
          </svg>
        </div>
        <span class="chatbot__arrow chatbot__arrow--left"></span>
        <p class='chatbot__message'>
         How Can I help You ?</p>
      </li>
      <!-- Message here -->
    </ul>
  </div>
  <div class="chatbot__entry chatbot--closed">
    <input type="text" class="chatbot__input" placeholder="Ask me " />
    <svg class="chatbot__submit" viewBox="0 0 32 32">
      <use xlink:href="#icon-send" />
    </svg>
  </div>
</div>

<!-- Symbols -->
<svg>
  <!-- Close icon -->
  <symbol id="icon-close" viewBox="0 0 32 32">
    <title>Close</title>
    <path d="M2.624 8.297l2.963-2.963 23.704 23.704-2.963 2.963-23.704-23.704z" />
    <path d="M2.624 29.037l23.704-23.704 2.963 2.963-23.704 23.704-2.963-2.963z" />
  </symbol>

  <!-- Speech icon -->
  <symbol id="icon-speech" viewBox="0 0 32 32">
    <title>Speech</title>
    <path style="fill: #ffffff; fill-rule: evenodd;" d="M21.795 5.333h-11.413c-0.038 0-0.077 0-0.114 0l-0.134 0.011v2.796c0.143-0.006 0.273-0.009 0.385-0.009h11.277c0.070 0 7.074 0.213 7.074 7.695 0 5.179-2.956 7.695-9.036 7.695h-3.792c-0.691 0-1.12 0.526-1.38 1.159l-1.387 3.093-1.625 3.77 0.245 0.453h2.56l2.538-5.678h2.837c7.633 0 11.84-3.727 11.84-10.494 0.001-8.564-7.313-10.492-9.875-10.492z" />
    <path style="fill: #ffffff; fill-rule: evenodd;" d="M10.912 24.259c-0.242-0.442-0.703-0.737-1.234-0.737-0 0-0 0-0 0h-0.56c-0.599-0.011-1.171-0.108-1.71-0.28l0.042 0.012c-1.82-0.559-4.427-2.26-4.427-7.424 0-6.683 5.024-7.597 7.109-7.686v-2.8c-2.042 0.095-9.91 1.067-9.91 10.483 0 4.832 1.961 7.367 3.606 8.64 1.38 1.067 3.109 1.744 4.991 1.843l0.033 0.019 2.805 5.211 1.41-3.273z" />
  </symbol>

  <!-- Send icon -->
  <symbol id="icon-send" viewBox="0 0 23.97 21.9">
    <title>Send</title>
    <path d="M0.31,9.43a0.5,0.5,0,0,0,0,.93l8.3,3.23L23.15,0Z"/>
    <path d="M9,14.6H9V21.4a0.5,0.5,0,0,0,.93.25L13.22,16l6,3.32A0.5,0.5,0,0,0,20,19l4-18.4Z"/>
  </symbol>

  <!-- Avatar icon -->
  <symbol id="avatar" width="32" height="32" viewBox="0 0 32 32">
    <title>Avatar</title>
        <circle id="oval" fill="#2F2E36" cx="16" cy="16" r="16"></circle>
        <g id="Group" transform="translate(7.000000, 0.000000)" fill-rule="nonzero">
            <g id="Shape">
                <polygon fill="#FFFFFF" points="3.60282353 20.1870588 19.0528302 12.91870588 16.5498113 3.60282353 16.5498113 3.60282353 14.6071698 10.905882 14.6071698 6.79282353 11.88 0 11.88 12 11.57 23.76 9.57 21.0328302 3.60282353 22.0328302"></polygon>
<!--                 <polygon fill="#FFFFFF" points="15.914717 11.88 13.8973585 15.7279245 11.88 11.88 7.92 11.88 12.0667925 19.0528302 12.0667925 23.76 15.6532075 23.76 15.6532075 19.0528302 19.8 11.88"></polygon> -->
                <polygon fill="#FFE600" points="23.43 0 0 8.58 23.43 4.43921739"></polygon>
            </g>
        </g>
  </symbol>

</svg>
{% endif %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/fetch/0.10.1/fetch.min.js'>

</script><script  src="{% static 'krishi_chaupal/js/script.js' %}"></script>

<script src="{%static 'krishi_chaupal/js/jquery-1.12.1.min.js' %}"></script>
<!-- popper js -->
<script src="{% static 'krishi_chaupal/js/popper.min.js' %}"></script>
<!-- bootstrap js -->
<script src="{%static 'krishi_chaupal/js/bootstrap.min.js'%}"></script>
<!-- easing js -->
<script src="{%static 'krishi_chaupal/js/jquery.magnific-popup.js'%}"></script>
<!-- swiper js -->
<script src="{%static 'krishi_chaupal/js/swiper.min.js'%}"></script>
<!-- swiper js -->
<script src="{%static 'krishi_chaupal/js/masonry.pkgd.js'%}"></script>
<!-- particles js -->
<script src="{%static 'krishi_chaupal/js/owl.carousel.min.js'%}"></script>
<script src="{%static 'krishi_chaupal/js/jquery.nice-select.min.js'%}"></script>
<!-- swiper js -->
<script src="{%static 'krishi_chaupal/js/slick.min.js'%}"></script>
<script src="{%static 'krishi_chaupal/js/jquery.counterup.min.js'%}"></script>
<script src="{%static 'krishi_chaupal/js/waypoints.min.js'%}"></script>
<!-- custom js -->
<script src="{%static 'krishi_chaupal/js/custom.js'%}"></script>
<script src="{%static 'krishi_chaupal/js/jquery-2.2.4.min.js'%}"></script>

  </body>
    </html>

KrishiChaupal/templates/faq.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<body>

    <!-- Header part end-->


    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>Frequenlty Asked Questions</h2>
                            <p><span><span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->


<!--Questions-Area -->
    <section id="questions_page" class="questions-area section-padding">
        <div class="container">
            <br> <br> <br>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="toggole-boxs">
                        <h3>Ques  1. What is farmer’s friend portal? </h3>
                        <div>
                            <p>Ans. This is a web portal designed to help the farmer to maximize its yield by providing necessary information like crop suggestion, crop prediction, adverse conditions of weather on crops, possible measures that can be taken by farmers, loan planning and various schemes etc.</p>
                        </div>
                        <h3>Ques 2. Who can use it?</h3>
                        <div>
                            <p>Ans. This is designed for farmers specially but it can also be beneficial if anyone wants to gather information about the crops and related information. This can also be used by government agencies and pesticides firms to provide the necessary information of different schemes launched by government and the possible pest attacks so that the farmer will be well prepared respectively.</p>
                        </div>
                        <h3>Ques 3. How to use the portal? </h3>
                        <div>
                            <p>Ans. You only need to sign up once and then login to use the portal.there also exist </p>
                        </div>
                        <h3>Ques 4. How I get the messege alert? </h3>
                        <div>
                            <p>Ans. When you sign up then you automatically registered for messege alert or you can also get the updates by just register your number once. </p>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="space-20 hidden visible-xs"></div>

                    <div class="toggole-boxs">
                        <h3>Ques  5. Do i get personalised messeges based on my location? </h3>
                        <div>
                            <p>Ans. yes, during sign up you will be asked your location. once you register then you will be provided personalised messeges.</p>
                        </div>
                        <h3>Ques  6. How can you suggest crop? </h3>
                        <div>
                            <p>Ans. You will be asked about the soil moisture content then based on your soil type you will be suggested the crops that can grows best on your field with minimum efforts and maximized outputs. </p>
                        </div>
                        <h3>Ques 7. Are you providing loans?</h3>
                        <div>
                            <p>Ans. No, we are not providing any type of loans we are only providing information regarding them.</p>
                        </div>
                        <h3>Ques 8. Are you selling seeds also?</h3>
                        <div>
                            <p>Ans. No, we are not seeling seeds. We are only predicting what kind of seeds will grow best according to your soil type.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- footer part start-->
    <footer class="footer-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-sm-6 col-md-4 col-xl-3">
                    <div class="single-footer-widget footer_1">
                        <a href="home.html"><center> <img src="img/logo.png" alt="" class="logo"></center> </a>
			<style>img.logo {
  height: 50%;
  width: 50%;
}
</style>
                        <p>This is a web portal designed specially to help farmer in providing them full assistance.</p>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xl-4">
                    <div class="single-footer-widget footer_2">
                        <h4>SMS Broadcast</h4>
                        <p>This service facilitate the farmer to get the information about any adverse weather condition instantly.
                        </p>
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Enter Phone Number'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter phone number'">
                                    <div class="input-group-append">
                                        <button class="btn btn_1" type="button"><i class="ti-angle-right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-md-4">
                    <div class="single-footer-widget footer_2">
                        <h4>Contact us</h4>
                        <div class="contact_info">
                            <p><span> Address :</span> Institute of Engineering and Technology<br>Jankipuram Sector F<br>Sitapur Road,Lucknow 226021<br></p>
                            <p><span> Phone : </span>+917007110758<br>  +917905770800<br> </p>
                            <p><span> Email :</span>1705210063@ietlucknow.ac.in<br>1705210057@ietlucknow.ac.in<br></p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </footer>
    <!-- footer part end-->




    <!-- jquery plugins here-->
    <!-- jquery -->
{% endblock %}